# Generated by Django 5.1.3 on 2024-11-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='market',
            new_name='markets',
        ),
    ]
