# Generated by Django 5.1.3 on 2024-11-09 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0002_rename_market_seller_markets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='market',
            new_name='markets',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='sellers',
        ),
    ]
