# Generated by Django 5.1.3 on 2024-11-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0007_remove_product_markets_remove_product_sellers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='markets',
            field=models.ManyToManyField(related_name='products', to='market_app.market'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sellers',
            field=models.ManyToManyField(related_name='products', to='market_app.seller'),
        ),
    ]
